name: Test Publish to TestPyPI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build the package
        run: |
          python -m build

      - name: Upload to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          twine upload --repository-url https://pypi.org/legacy/ dist/*
