name: Publish to TestPyPI

on:
  workflow_dispatch:
  release:
    types: [prereleased]  # <= Par exemple, uniquement les pre-releases

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish-test:
    runs-on: ubuntu-latest
    environment: testpypi

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: python -m pip install --upgrade pip build twine

      - run: python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
